# Generated by Django 5.1.7 on 2025-03-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department to which the user belongs. (Required for students)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Semester number for student (1-8)', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
