# Generated by Django 5.1.7 on 2025-03-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_remove_question_time_stamp_question_popup_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, help_text='The selected choice by the student', null=True, on_delete=django.db.models.deletion.CASCADE, to='college.choice'),
        ),
    ]
