# Generated by Django 5.1.7 on 2025-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_answer_selected_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('faculty', 'Faculty'), ('class_advisor', 'Class Advisor'), ('hod', 'Head of Department'), ('student', 'Student')], max_length=20),
        ),
    ]
