# Generated by Django 5.1.7 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('faculty', 'Faculty'), ('class_advisor', 'Class Advisor'), ('hod', 'Head of Department'), ('student', 'Student')], max_length=20),
        ),
    ]
